name: Install DCAP libraries
description: Installs the DCAP libraries into the environment
inputs: 
  version:
    description: "The version of the DCAP libs to install"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Installing DCAP libraries
      shell: bash
      run:
        DCAP_VERSION=${{ inputs.version }}
        source /etc/lsb-release &&
        sudo mkdir -p /etc/apt/keyrings &&
        wget -qO - https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key | gpg --dearmor | sudo tee /etc/apt/keyrings/intel-sgx.gpg > /dev/null &&
        echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/intel-sgx.gpg] https://download.01.org/intel-sgx/sgx_repo/ubuntu $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/intel-sgx.list
        sudo apt-get update &&
        sudo apt-get install -y libsgx-dcap-ql${DCAP_VERSION:+"=${DCAP_VERSION}"} libsgx-dcap-ql-dev${DCAP_VERSION:+"=${DCAP_VERSION}"} &&
        sudo apt-get install -y libsgx-dcap-quote-verify${DCAP_VERSION:+"=${DCAP_VERSION}"} libsgx-dcap-quote-verify-dev${DCAP_VERSION:+"=${DCAP_VERSION}"}
