name: Install SGX SDK
description: Installs the Intel SGX SDK (and propagates environment variables)
inputs: 
  version:
    description: "The version of the SDK to install"
    required: false
    default: "2.17.101.1"

runs:
  using: composite
  steps:
    - name: Install SGX SDK
      shell: bash
      # In order to propagate the environment variables to subsequent steps we
      # need to redirect through $GITHUB_ENV, see
      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
      # We can't do `cat /opt/intel/sgxsdk/environment >> $GITHUB_ENV` because
      # the environment file has _logic_ which the `GITHUB_ENV` parser will
      # fail on.  So we manually pass on the known environment variables.
      run:
        source /etc/lsb-release &&
        wget "https://download.01.org/intel-sgx/sgx-linux/`echo ${{ inputs.version }} | cut -d '.' -f1-2`/distro/ubuntu${DISTRIB_RELEASE}-server/sgx_linux_x64_sdk_${{ inputs.version }}.bin" &&
        chmod +x ./sgx_linux_x64_sdk_${{ inputs.version }}.bin &&
        ./sgx_linux_x64_sdk_${{ inputs.version }}.bin --prefix=/opt/intel &&
        source /opt/intel/sgxsdk/environment &&
        echo "SGX_SDK=$SGX_SDK" >> $GITHUB_ENV &&
        echo "PATH=$PATH" >> $GITHUB_ENV &&
        echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> $GITHUB_ENV &&
        echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> $GITHUB_ENV

